/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_tron_common_crypto_ckzg4844_CKZG4844JNI */

#ifndef _Included_org_tron_common_crypto_ckzg4844_CKZG4844JNI
#define _Included_org_tron_common_crypto_ckzg4844_CKZG4844JNI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_tron_common_crypto_ckzg4844_CKZG4844JNI_BYTES_PER_COMMITMENT
#define org_tron_common_crypto_ckzg4844_CKZG4844JNI_BYTES_PER_COMMITMENT 48L
#undef org_tron_common_crypto_ckzg4844_CKZG4844JNI_BYTES_PER_PROOF
#define org_tron_common_crypto_ckzg4844_CKZG4844JNI_BYTES_PER_PROOF 48L
#undef org_tron_common_crypto_ckzg4844_CKZG4844JNI_BYTES_PER_FIELD_ELEMENT
#define org_tron_common_crypto_ckzg4844_CKZG4844JNI_BYTES_PER_FIELD_ELEMENT 32L
#undef org_tron_common_crypto_ckzg4844_CKZG4844JNI_FIELD_ELEMENTS_PER_BLOB
#define org_tron_common_crypto_ckzg4844_CKZG4844JNI_FIELD_ELEMENTS_PER_BLOB 4096L
#undef org_tron_common_crypto_ckzg4844_CKZG4844JNI_BYTES_PER_BLOB
#define org_tron_common_crypto_ckzg4844_CKZG4844JNI_BYTES_PER_BLOB 131072L

/*
 * Class:     org_tron_common_crypto_ckzg4844_CKZG4844JNI
 * Method:    loadTrustedSetup
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_tron_common_crypto_ckzg4844_CKZG4844JNI_loadTrustedSetup__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_tron_common_crypto_ckzg4844_CKZG4844JNI
 * Method:    loadTrustedSetup
 * Signature: ([BJ[BJ)V
 */
JNIEXPORT void JNICALL Java_org_tron_common_crypto_ckzg4844_CKZG4844JNI_loadTrustedSetup___3BJ_3BJ
  (JNIEnv *, jclass, jbyteArray, jlong, jbyteArray, jlong);

/*
 * Class:     org_tron_common_crypto_ckzg4844_CKZG4844JNI
 * Method:    freeTrustedSetup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_tron_common_crypto_ckzg4844_CKZG4844JNI_freeTrustedSetup
  (JNIEnv *, jclass);

/*
 * Class:     org_tron_common_crypto_ckzg4844_CKZG4844JNI
 * Method:    blobToKzgCommitment
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tron_common_crypto_ckzg4844_CKZG4844JNI_blobToKzgCommitment
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     org_tron_common_crypto_ckzg4844_CKZG4844JNI
 * Method:    computeKzgProof
 * Signature: ([B[B)Lorg/tron/common/crypto/ckzg4844/ProofAndY;
 */
JNIEXPORT jobject JNICALL Java_org_tron_common_crypto_ckzg4844_CKZG4844JNI_computeKzgProof
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     org_tron_common_crypto_ckzg4844_CKZG4844JNI
 * Method:    computeBlobKzgProof
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_tron_common_crypto_ckzg4844_CKZG4844JNI_computeBlobKzgProof
  (JNIEnv *, jclass, jbyteArray, jbyteArray);

/*
 * Class:     org_tron_common_crypto_ckzg4844_CKZG4844JNI
 * Method:    verifyKzgProof
 * Signature: ([B[B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_tron_common_crypto_ckzg4844_CKZG4844JNI_verifyKzgProof
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_tron_common_crypto_ckzg4844_CKZG4844JNI
 * Method:    verifyBlobKzgProof
 * Signature: ([B[B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_org_tron_common_crypto_ckzg4844_CKZG4844JNI_verifyBlobKzgProof
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     org_tron_common_crypto_ckzg4844_CKZG4844JNI
 * Method:    verifyBlobKzgProofBatch
 * Signature: ([B[B[BJ)Z
 */
JNIEXPORT jboolean JNICALL Java_org_tron_common_crypto_ckzg4844_CKZG4844JNI_verifyBlobKzgProofBatch
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jbyteArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
